version: "3"

services:
  tester_app:
    build: tester
    depends_on:
      test_db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
      - spring-postgres

  test_db:
    image: postgres:12.2
    container_name: test_db
    restart: always
    volumes:
      - ./tester_db/BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${POSTGRESUSER}
      - POSTGRES_PASSWORD=${POSTGRESPASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
volumes:
  db-data:
networks:
  spring-postgres: